package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoRegistro;
import fatec.poo.model.Recepcionista;
import fatec.poo.control.DaoRecepcionista;
import fatec.poo.model.Registro;
import fatec.poo.control.DaoQuarto;
import fatec.poo.model.Quarto;
import fatec.poo.control.DaoHospede;
import fatec.poo.model.Hospede;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;

import javax.swing.JOptionPane;

/**
 *
 * @author Adriana, Danielle e Franciele
 */
public class GuiReservaLiberacao extends javax.swing.JFrame {

    /**
     * Creates new form GuiReservaLiberacao
     */
    public GuiReservaLiberacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigo = new javax.swing.JLabel();
        lblRegistroFuncional = new javax.swing.JLabel();
        lblCPFHospede = new javax.swing.JLabel();
        lblNQuarto = new javax.swing.JLabel();
        lblDataEntrada = new javax.swing.JLabel();
        lblDataSaida = new javax.swing.JLabel();
        lblValorHospedagem = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtRegistroFuncional = new javax.swing.JTextField();
        txtNQuarto = new javax.swing.JTextField();
        txtValorHospedagem = new javax.swing.JTextField();
        txtBuscaRegistroFuncional = new javax.swing.JTextField();
        txtBuscaCPFHospede = new javax.swing.JTextField();
        txtSituacao = new javax.swing.JTextField();
        btnReservar = new javax.swing.JButton();
        btnLiberar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtCPFHospede = new javax.swing.JFormattedTextField();
        txtDataEntrada = new javax.swing.JFormattedTextField();
        txtDataSaida = new javax.swing.JFormattedTextField();
        btnBuscaRegistroFuncional = new javax.swing.JButton();
        btnBuscaCPFHospede = new javax.swing.JButton();
        btnBuscaSituacao = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Hospedagem");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblCodigo.setText("Código");

        lblRegistroFuncional.setText("Registro Funcional");

        lblCPFHospede.setText("CPF Hóspede");

        lblNQuarto.setText("N°. Quarto");

        lblDataEntrada.setText("Data entrada");

        lblDataSaida.setText("Data saída");

        lblValorHospedagem.setText("Valor Hospedagem");

        lblSituacao.setText("Situação");
        lblSituacao.setEnabled(false);

        txtRegistroFuncional.setEnabled(false);

        txtNQuarto.setEnabled(false);

        txtValorHospedagem.setEnabled(false);

        txtBuscaRegistroFuncional.setEnabled(false);

        txtBuscaCPFHospede.setEnabled(false);

        txtSituacao.setEnabled(false);

        btnReservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/save.png"))); // NOI18N
        btnReservar.setText("Reservar");
        btnReservar.setEnabled(false);
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnLiberar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/rem.png"))); // NOI18N
        btnLiberar.setText("Liberar");
        btnLiberar.setEnabled(false);
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        try {
            txtCPFHospede.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFHospede.setEnabled(false);

        try {
            txtDataEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataEntrada.setEnabled(false);

        try {
            txtDataSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataSaida.setEnabled(false);

        btnBuscaRegistroFuncional.setText("...");
        btnBuscaRegistroFuncional.setEnabled(false);
        btnBuscaRegistroFuncional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaRegistroFuncionalActionPerformed(evt);
            }
        });

        btnBuscaCPFHospede.setText("...");
        btnBuscaCPFHospede.setEnabled(false);
        btnBuscaCPFHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaCPFHospedeActionPerformed(evt);
            }
        });

        btnBuscaSituacao.setText("...");
        btnBuscaSituacao.setEnabled(false);
        btnBuscaSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaSituacaoActionPerformed(evt);
            }
        });

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNQuarto)
                    .addComponent(lblDataEntrada)
                    .addComponent(lblDataSaida)
                    .addComponent(lblValorHospedagem)
                    .addComponent(lblRegistroFuncional)
                    .addComponent(lblCPFHospede)
                    .addComponent(lblCodigo))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRegistroFuncional, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCPFHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 108, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscaCPFHospede)
                            .addComponent(btnBuscaRegistroFuncional)
                            .addComponent(lblSituacao))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscaSituacao)
                                .addGap(18, 18, 18)
                                .addComponent(txtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtBuscaRegistroFuncional, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                                .addComponent(txtBuscaCPFHospede)))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorHospedagem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNQuarto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDataSaida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addComponent(txtDataEntrada, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 203, Short.MAX_VALUE)
                        .addComponent(btnConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnReservar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLiberar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair)
                        .addGap(74, 74, 74))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistroFuncional)
                    .addComponent(txtRegistroFuncional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscaRegistroFuncional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaRegistroFuncional))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCPFHospede)
                            .addComponent(txtCPFHospede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscaCPFHospede))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNQuarto)
                            .addComponent(txtNQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txtBuscaCPFHospede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSituacao)
                            .addComponent(txtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscaSituacao))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDataEntrada)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataSaida)
                            .addComponent(txtDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorHospedagem)
                            .addComponent(txtValorHospedagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSair)
                            .addComponent(btnLiberar)
                            .addComponent(btnReservar)
                            .addComponent(btnConsultar))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

        registro = null;

        if(txtCodigo.getText().matches("[0-9]*")){ //valor digitao é inteiro
            registro = daoRegistro.consultar(Integer.parseInt(txtCodigo.getText()));
        
            if (registro == null){//não encontrou o objeto no BD
               txtCodigo.setEnabled(false);
               txtRegistroFuncional.setEnabled(true);
               btnBuscaRegistroFuncional.setEnabled(true);
               txtBuscaRegistroFuncional.setEnabled(false);
               txtCPFHospede.setEnabled(false);
               btnBuscaCPFHospede.setEnabled(false);
               txtBuscaCPFHospede.setEnabled(false);
               txtNQuarto.setEnabled(false);
               btnBuscaSituacao.setEnabled(false);
               txtSituacao.setEnabled(false);
               txtDataEntrada.setEnabled(false);
               txtDataSaida.setEnabled(false);
               txtValorHospedagem.setEnabled(false);

               btnConsultar.setEnabled(false);
               btnReservar.setEnabled(true);
           }
           else{ //encontrou o objeto no BD
                
              txtRegistroFuncional.setText(String.valueOf(registro.getRecepcionista()));
              txtCPFHospede.setText(String.valueOf(registro.getHospede()));
              txtNQuarto.setText(String.valueOf(registro.getQuarto()));
              txtDataEntrada.setText(String.valueOf(registro.getDataEntrada()));
              txtDataSaida.setText(String.valueOf(registro.getDataEntrada()));

              txtCodigo.setEnabled(false); 
              btnConsultar.setEnabled(false);
              
              if(txtDataSaida == null){
                  btnLiberar.setEnabled(true);
                  txtDataSaida.setEnabled(true);
                  txtDataSaida.requestFocus();
              }else{
                  try { //data válida:
                    LocalDate.parse(txtDataSaida.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                  }catch (DateTimeParseException e) { //data inválida:
                    JOptionPane.showMessageDialog(null, "Data inválida! Digite novamente.");
                    txtDataSaida.setText(null);
                    txtDataSaida.requestFocus();
                }
              }
           } 
       }
        else{ //<> de inteiro
          JOptionPane.showMessageDialog(null, "Código de Registro inválido! Digite novamente.");
          txtCodigo.setText(null);
          txtCodigo.requestFocus();
       }
    }//GEN-LAST:event_btnConsultarActionPerformed
                                        
    private void btnBuscaRegistroFuncionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaRegistroFuncionalActionPerformed
        daoRecepcionista = new DaoRecepcionista(conexao.conectar());
        recepcionista = daoRecepcionista.consultar(Integer.parseInt(txtRegistroFuncional.getText()));
        //INSTANCIAR OBJ REGISTRO AQUI 
        registro = new Registro(Integer.parseInt(txtCodigo.getText()), LocalDate.parse(txtDataEntrada.getText()), recepcionista);
        
        if (recepcionista == null){//não encontrou o objeto na BD
            JOptionPane.showMessageDialog(null, "Recepcionista não cadastrado!");
            txtRegistroFuncional.setText(null);
            txtRegistroFuncional.requestFocus();
        }
        else{ //encontrou o objeto na BD
            txtBuscaRegistroFuncional.setEnabled(true);
            txtBuscaRegistroFuncional.setText(recepcionista.getNome());
            
            txtRegistroFuncional.setEnabled(false); 
            txtCPFHospede.setEnabled(true);
          
            btnConsultar.setEnabled(false);
            btnBuscaCPFHospede.setEnabled(true);
        }
    }//GEN-LAST:event_btnBuscaRegistroFuncionalActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("BD2213025","BD2213025"); //usuario e senha
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@192.168.1.6:1521:xe");
                                                     //192.168.1.6 -> FATEC
        daoRegistro = new DaoRegistro(conexao.conectar());
        daoQuarto = new DaoQuarto(conexao.conectar());
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        conexao.fecharConexao();
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed
        //txtValorHospedagem.setText(String.valueOf(quarto.liberar(registro.getDataEntrada().until(registro.getDataSaida(), ChronoUnit.DAYS))));
        txtValorHospedagem.setText(String.valueOf(registro.liberarQuarto()));
        
        registro = new Registro(Integer.parseInt(txtCodigo.getText()), LocalDate.parse(txtDataEntrada.getText()), recepcionista);
        daoRegistro.liberar(registro);  
    }//GEN-LAST:event_btnLiberarActionPerformed

    private void btnBuscaCPFHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaCPFHospedeActionPerformed
        daoHospede = new DaoHospede(conexao.conectar());
        hospede = daoHospede.consultar(txtCPFHospede.getText());
        //INSTANCIAR OBJ REGISTRO AQUI 
        registro = new Registro(Integer.parseInt(txtCodigo.getText()), LocalDate.parse(txtDataEntrada.getText()), recepcionista);
        
       if (hospede == null){//não encontrou o objeto na BD
            JOptionPane.showMessageDialog(null, "Hospede não cadastrado!");
            txtCPFHospede.setText(null);
            txtCPFHospede.requestFocus();
        }
        else{ //encontrou o objeto na BD
            txtBuscaCPFHospede.setEnabled(true); 
            txtBuscaCPFHospede.setText(hospede.getNome());
            hospede.addRegistro(registro);
            
            txtCPFHospede.setEnabled(false); 
            txtNQuarto.setEnabled(true);
          
            btnBuscaCPFHospede.setEnabled(false);
            btnBuscaSituacao.setEnabled(true);
        }
    }//GEN-LAST:event_btnBuscaCPFHospedeActionPerformed

    private void btnBuscaSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaSituacaoActionPerformed
        quarto = daoQuarto.consultar(Integer.parseInt(txtNQuarto.getText()));
        //INSTANCIAR OBJ REGISTRO AQUI 
        registro = new Registro(Integer.parseInt(txtCodigo.getText()), LocalDate.parse(txtDataEntrada.getText()), recepcionista);
        
       if (quarto == null){//não encontrou o objeto na BD
            JOptionPane.showMessageDialog(null, "Quarto não cadastrado!");
            txtNQuarto.setText(null);
            txtNQuarto.requestFocus();
        }
        else{ //encontrou o objeto na BD
           
           if(quarto.getSituacao() == true){ //se o quarto estiver true (ocupado)
               JOptionPane.showMessageDialog(null, "Quarto ocupado!");
               txtNQuarto.setText(null);
               txtNQuarto.requestFocus();
           }           
           else{ //se o quarto estiver false (livre)
               txtSituacao.setText("Quarto livre!");
               //registro.setQuarto(quarto); //ligacao entre registro e quarto
               
               txtDataEntrada.setEnabled(true);
               btnReservar.setEnabled(true);
           }
        }
    }//GEN-LAST:event_btnBuscaSituacaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaCPFHospede;
    private javax.swing.JButton btnBuscaRegistroFuncional;
    private javax.swing.JButton btnBuscaSituacao;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLiberar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblCPFHospede;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDataEntrada;
    private javax.swing.JLabel lblDataSaida;
    private javax.swing.JLabel lblNQuarto;
    private javax.swing.JLabel lblRegistroFuncional;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblValorHospedagem;
    private javax.swing.JTextField txtBuscaCPFHospede;
    private javax.swing.JTextField txtBuscaRegistroFuncional;
    private javax.swing.JFormattedTextField txtCPFHospede;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtDataEntrada;
    private javax.swing.JFormattedTextField txtDataSaida;
    private javax.swing.JTextField txtNQuarto;
    private javax.swing.JTextField txtRegistroFuncional;
    private javax.swing.JTextField txtSituacao;
    private javax.swing.JTextField txtValorHospedagem;
    // End of variables declaration//GEN-END:variables
    private DaoRegistro daoRegistro=null;
    private Registro registro=null;
    private DaoRecepcionista daoRecepcionista=null;
    private Recepcionista recepcionista=null;
    private DaoQuarto daoQuarto=null;
    private Hospede hospede=null;
    private DaoHospede daoHospede=null;
    private Quarto quarto=null;
    private Conexao conexao=null;
}
